# Generated by Django 2.2.5 on 2019-10-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
