# Generated by Django 2.2.5 on 2019-10-21 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20191019_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.Category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Videos_sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos_sold', models.ManyToManyField(to='account.Book')),
            ],
        ),
    ]
