# Generated by Django 2.2.5 on 2019-10-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_buyer_prueba_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_prueba',
            name='news_name_prueba',
            field=models.CharField(max_length=100),
        ),
    ]
