# Generated by Django 2.2.5 on 2019-10-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20191023_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='video_stored',
            field=models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.Book', verbose_name='Book'),
        ),
    ]
