# Generated by Django 2.2.5 on 2019-10-25 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0017_remove_buyer_video_stored'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, max_length=255)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('price', models.IntegerField()),
                ('price_exclusive', models.IntegerField()),
                ('minutes_exclusive', models.IntegerField(default='0')),
                ('category', models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.Category', verbose_name='Category')),
                ('news_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
