# Generated by Django 2.2.5 on 2019-10-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Watermark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkin', models.IntegerField()),
            ],
        ),
    ]
