# Generated by Django 2.2.5 on 2019-10-30 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0019_create_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_watermark',
            field=models.FileField(default='', upload_to='books/watermark/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, max_length=255)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('video_watermark', models.FileField(upload_to='books/watermark/')),
                ('price', models.IntegerField()),
                ('price_exclusive', models.IntegerField()),
                ('minutes_exclusive', models.IntegerField(default='0')),
                ('category', models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.Category', verbose_name='Category')),
                ('news_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
