# Generated by Django 2.2.5 on 2019-10-31 02:27

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20191030_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='incident_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cart',
            name='incident_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='news',
            name='incident_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='news',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
