# Generated by Django 2.2.5 on 2019-11-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20191101_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('less_10M', models.IntegerField()),
                ('less_50M', models.IntegerField()),
                ('less_100M', models.IntegerField()),
                ('less_150M', models.IntegerField()),
                ('local_less_10M', models.IntegerField()),
                ('local_less_50M', models.IntegerField()),
                ('local_less_100M', models.IntegerField()),
                ('local_less_150M', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='author',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='buyers_prueba',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='category',
        ),
        migrations.DeleteModel(
            name='Buyer_Prueba',
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
