# Generated by Django 2.2.5 on 2019-11-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20191108_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_news',
            field=models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.News_Type', verbose_name='News_Type'),
        ),
    ]
