# Generated by Django 2.2.5 on 2019-11-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20191108_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_type',
            options={'verbose_name_plural': 'News_Types'},
        ),
    ]
