# Generated by Django 2.2.5 on 2019-11-11 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0032_auto_20191108_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_email', models.EmailField(max_length=70, null=True, unique=True)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('type_news', models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.News_Type', verbose_name='News_Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
