# Generated by Django 2.2.5 on 2019-11-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='watermark_ready',
            field=models.BooleanField(default=False),
        ),
    ]
