# Generated by Django 2.2.5 on 2019-11-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_news_watermark_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='watermark_ready',
        ),
        migrations.AddField(
            model_name='book',
            name='watermark_ready',
            field=models.BooleanField(default=False),
        ),
    ]
