# Generated by Django 2.2.5 on 2019-11-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20191111_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='buyers',
        ),
    ]
