# Generated by Django 2.2.5 on 2019-11-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_remove_book_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='if_seller',
            field=models.BooleanField(default=False),
        ),
    ]
