# Generated by Django 2.2.5 on 2019-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_userprofile_if_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
