# Generated by Django 2.2.5 on 2019-11-13 20:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0038_userprofile_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, max_length=255)),
                ('price', models.IntegerField()),
                ('transacion_date', models.DateField(default=datetime.date.today)),
                ('incident_date', models.DateField(default=datetime.date.today)),
                ('country', models.CharField(max_length=30)),
                ('book_id', models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.DO_NOTHING, to='account.Book', verbose_name='Book')),
                ('if_seller', models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile', verbose_name='UserProfile')),
                ('news_id', models.ForeignKey(default='1 ', on_delete=django.db.models.deletion.DO_NOTHING, to='account.News', verbose_name='News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
