# Generated by Django 2.2.5 on 2019-11-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='if_seller',
        ),
    ]
