# Generated by Django 2.2.5 on 2019-11-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_remove_account_if_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='book_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='news_id',
            field=models.CharField(max_length=100),
        ),
    ]
