# Generated by Django 2.2.5 on 2019-11-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20191116_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
