# Generated by Django 2.2.5 on 2019-11-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20191116_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
